const LOAD_POSTS_IN_PROGRESS = "POSTS::LOAD_POSTS_IN_PROGRESS";
const LOAD_POSTS_ERROR = "POSTS::LOAD_POSTS_ERROR";
const LOAD_POSTS_SUCCESS = "POSTS::LOAD_POSTS_SUCCESS";
export {LOAD_POSTS_IN_PROGRESS, LOAD_POSTS_ERROR, LOAD_POSTS_SUCCESS};